apiVersion: v1
kind: Secret
metadata:
  name: inventory-db
  namespace: apps
type: Opaque
stringData:
  DB_HOST: "pfe-inventory-db.c7mg8qiweece.eu-west-3.rds.amazonaws.com"  # ex: inventory.xxxxx.eu-west-3.rds.amazonaws.com
  DB_PORT: "5432"
  DB_NAME: "inventory"
  DB_USER: "app_user"
  DB_PASS: "ChangeMe42!"
