apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-inventory
  namespace: apps
  annotations:
    # Quand on activera Secrets Manager CSI ou autres accès AWS, on remplacera par le rôle IRSA:
    # eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/<ROLE_NAME_FOR_INVENTORY>
  labels:
    app: inventory
