apiVersion: v1
kind: ConfigMap
metadata:
  name: billing-config
  namespace: apps
data:
  PORT: "8080"
  QUEUE_NAME: "billing_queue"
  RABBITMQ_URL: "amqp://billing:ChangeMe42!@rabbitmq.rabbitmq.svc.cluster.local:5672"
