apiVersion: v1
kind: Secret
metadata:
  name: billing-db
  namespace: apps
type: Opaque
stringData:
  DB_HOST: "pfe-inventory-db.c7mg8qiweece.eu-west-3.rds.amazonaws.com"   # remplacera par endpoint RDS billing plus tard
  DB_PORT: "5432"
  DB_NAME: "billing"
  DB_USER: "app_user"
  DB_PASS: "ChangeMe42!"
